"""Add User SNP

Revision ID: 752153e2c42b
Revises: 3deaba67b4c2
Create Date: 2024-07-16 09:07:41.051378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752153e2c42b'
down_revision: Union[str, None] = '3deaba67b4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=False))
    op.add_column('users', sa.Column('surname', sa.String(length=64), nullable=False))
    op.add_column('users', sa.Column('patronymic', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'patronymic')
    op.drop_column('users', 'surname')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
